# Generated by Django 5.2.3 on 2025-06-24 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the menu item.', max_length=100, unique=True)),
                ('url', models.URLField(blank=True, help_text='URL the menu item links to (e.g., /about or https://example.com).', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the menu item should appear.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this menu item should be displayed.')),
                ('parent', models.ForeignKey(blank=True, help_text='For nested menu items (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
